--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/ishan/Pictures/wallpapers/Lake.jpg"

-- Special
background="#0a080b"
foreground="#cdbfdd"
cursor="#cdbfdd"

-- Colors
color0="#0a080b"
color1="#513A85"
color2="#6F5A94"
color3="#9B6EA5"
color4="#C87BA1"
color5="#B187BC"
color6="#D68EB4"
color7="#cdbfdd"
color8="#8f859a"
color9="#513A85"
color10="#6F5A94"
color11="#9B6EA5"
color12="#C87BA1"
color13="#B187BC"
color14="#D68EB4"
color15="#cdbfdd"
