# Shell variables
# Generated by 'wal'
wallpaper='/home/ishan/Pictures/wallpapers/Lake.jpg'

# Special
background='#0a080b'
foreground='#cdbfdd'
cursor='#cdbfdd'

# Colors
color0='#0a080b'
color1='#513A85'
color2='#6F5A94'
color3='#9B6EA5'
color4='#C87BA1'
color5='#B187BC'
color6='#D68EB4'
color7='#cdbfdd'
color8='#8f859a'
color9='#513A85'
color10='#6F5A94'
color11='#9B6EA5'
color12='#C87BA1'
color13='#B187BC'
color14='#D68EB4'
color15='#cdbfdd'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
