# Shell variables
# Generated by 'wal'
wallpaper='/home/ishan/Pictures/wallpapers/Lofi-Urban-Nightscape.png'

# Special
background='#05870A'
foreground='#8fd4d3'
cursor='#8fd4d3'

# Colors
color0='#05870A'
color1='#5D5752'
color2='#8AD072'
color3='#0A9B50'
color4='#156965'
color5='#2D6B69'
color6='#103D99'
color7='#8fd4d3'
color8='#649493'
color9='#5D5752'
color10='#8AD072'
color11='#0A9B50'
color12='#156965'
color13='#2D6B69'
color14='#103D99'
color15='#8fd4d3'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
